az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat01 --name bobagency-config --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat01 --name bobauditservice-config --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat01 --name bobburs-config --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat01 --name bobfileprocessing-config --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat01 --name boblogger-config --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat01 --name bobmposinterface-config --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat01 --name boboag-config --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat01 --name bobonegov-config --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat01 --name bobpaymentapi-config --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat01 --name bobqueuemanager-config --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat01 --name bobreferencing-config --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat01 --name bobreporting-config --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat01 --name boburm-config --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat01 --name bobuserlimits-config --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat01 --name novatrackapp-config --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat01 --name novatracklogger-config --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat01 --name novatrackurm-config --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat02 --name bobagency-data --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat02 --name bobauditservice-data --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat02 --name bobburs-data --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat02 --name bobfileprocessing-data --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat02 --name boblogger-data --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat02 --name bobmposinterface-data --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat02 --name boboag-data --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat02 --name bobonegov-data --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat02 --name bobpaymentapi-data --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat02 --name bobqueuemanager-data --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat02 --name bobreferencing-data --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat02 --name bobreporting-data --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat02 --name boburm-data --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat02 --name bobuserlimits-data --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat02 --name novatrackapp-data --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat02 --name novatracklogger-data --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat02 --name novatrackurm-data --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat03 --name bobagency-log --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat03 --name bobauditservice-log --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat03 --name bobburs-log --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat03 --name bobfileprocessing-log --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat03 --name boblogger-log --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat03 --name bobmposinterface-log --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat03 --name boboag-log --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat03 --name bobonegov-log --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat03 --name bobpaymentapi-log --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat03 --name bobqueuemanager-log --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat03 --name bobreferencing-log --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat03 --name bobreporting-log --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat03 --name boburm-log --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat03 --name bobuserlimits-log --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat03 --name novatrackapp-log --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat03 --name novatracklogger-log --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat03 --name novatrackurm-log --enabled-protocols SMB

az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat01 --name bobr3portal-config --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat02 --name bobr3portal-data --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat03 --name bobr3portal-log --enabled-protocols SMB

#az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat01 --name bitnami-config --enabled-protocols SMB
#az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat02 --name bitnami-data --enabled-protocols SMB
#az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat03 --name bitnami-log --enabled-protocols SMB

az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat01 --name keycloak-config --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat02 --name keycloak-data --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat03 --name keycloak-log --enabled-protocols SMB

az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat01 --name bobmessaging-config --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat02 --name bobmessaging-data --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat03 --name bobmessaging-log --enabled-protocols SMB

az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat01 --name novatrackkeycloak-config --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat02 --name novatrackkeycloak-data --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat03 --name novatrackkeycloak-log --enabled-protocols SMB

az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat01 --name novatrackmessaging-config --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat02 --name novatrackmessaging-data --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat03 --name novatrackmessaging-log --enabled-protocols SMB

az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat01 --name novatrackauditservice-config --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat02 --name novatrackauditservice-data --enabled-protocols SMB
az storage share-rm create --resource-group rg-dcrs-uat-01 --storage-account n0vdcrsuat03 --name novatrackauditservice-log --enabled-protocols SMB
