apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bobsignage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bobsignage
  template:
    metadata:
      labels:
        app: bobsignage
    spec:
      containers:
        - name: bobsignage
          image: cregdcrsuat01.azurecr.io/bobsignage:latest
          ports:
            - containerPort: 3008
          envFrom:
            - configMapRef:
                name: signage-config
          volumeMounts:
            - name: bobsignage-config
              mountPath: /app/config
            - name: bobsignage-data
              mountPath: /app/data
            - name: bobsignage-log
              mountPath: /app/log
      volumes:
        - name: bobsignage-config
          persistentVolumeClaim:
            claimName: bobsignage-config
        - name: bobsignage-data
          persistentVolumeClaim:
            claimName: bobsignage-data
        - name: bobsignage-log
          persistentVolumeClaim:
            claimName: bobsignage-log
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bobr3portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bobr3portal
  template:
    metadata:
      labels:
        app: bobr3portal
    spec:
      containers:
        - name: bobr3portal
          image: cregdcrsuat01.azurecr.io/bobr3portal:latest
          ports:
            - containerPort: 3006
          envFrom:
            - configMapRef:
                name: bobr3portal-config
          volumeMounts:
            - name: bobr3portal-config
              mountPath: /app/config
            - name: bobr3portal-data
              mountPath: /app/data
            - name: bobr3portal-log
              mountPath: /root/.npm/_logs
      volumes:
        - name: bobr3portal-config
          persistentVolumeClaim:
            claimName: bobr3portal-config
        - name: bobr3portal-data
          persistentVolumeClaim:
            claimName: bobr3portal-data
        - name: bobr3portal-log
          persistentVolumeClaim:
            claimName: bobr3portal-log
