apiVersion: v1
kind: Service
metadata:
  name: keycloak
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: keycloak
  type: LoadBalancer
  loadBalancerIP: 10.210.5.26
  ports:
  - port: 8085
    targetPort: 8443
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
spec:
  replicas: 1
  serviceName: keycloak
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:latest
          args: ["start"]
          env:
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
            - name: KEYCLOAK_USER
              value: admin
            - name: KEYCLOAK_PASSWORD
              value: admin
            - name: KC_HOSTNAME
              value: keycloak.novusware.com.sg
            - name: KC_HTTPS_CERTIFICATE_FILE
              value: /etc/x509/https/tls.crt
            - name: KC_HTTPS_CERTIFICATE_KEY_FILE
              value: /etc/x509/https/tls.key
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: "jdbc:postgresql://postgres.novusware.com.sg:5432/keycloak?user=postgres&password=postgres"
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: keycloak-config
              mountPath: /opt/keycloak/conf
#            - name: keycloak-data
#              mountPath: /opt/keycloak/data/h2
            - name: keycloak-log
              mountPath: /opt/keycloak/logs
            - name: keycloak-config
              mountPath: /etc/x509/https/tls.crt
              subPath: fullchain.pem
            - name: keycloak-config
              mountPath: /etc/x509/https/tls.key
              subPath: privkey.pem
      volumes:
        - name: keycloak-config
          persistentVolumeClaim:
            claimName: keycloak-config
        - name: keycloak-data
          persistentVolumeClaim:
            claimName: keycloak-data
        - name: keycloak-log
          persistentVolumeClaim:
            claimName: keycloak-log
