apiVersion: v1
kind: Service
metadata:
  name: keycloak
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: keycloak
  type: LoadBalancer
  ports:
  - port: 8085
    targetPort: 8080
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
spec:
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:21.0.2
          args: ["start-dev"]
          ports:
            - containerPort: 8080
          env:
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
            - name: KEYCLOAK_USER
              value: admin
            - name: KEYCLOAK_PASSWORD
              value: admin
            - name: KEYCLOAK_IMPORT
              value: /tmp/realm.json
            - name: DB_VENDOR
              value: postgres
            - name: DB_ADDR
              value: localhost:5432
            - name: DB_DATABASE
              value: keycloak
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
          volumeMounts:
            - name: keycloak-config
              mountPath: /tmp/realm.json
              subPath: realm.json
            - name: keycloak-data
              mountPath: /data/keycloak
            - name: keycloak-log
              mountPath: /opt/keycloak/logs
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: keycloak
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: keycloak-postgres-data-01
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: keycloak-config
          persistentVolumeClaim:
            claimName: keycloak-config
        - name: keycloak-data
          persistentVolumeClaim:
            claimName: keycloak-data
        - name: keycloak-log
          persistentVolumeClaim:
            claimName: keycloak-log
        - name: keycloak-postgres-data-01
          persistentVolumeClaim:
            claimName: keycloak-postgres-data-01
