apiVersion: v1
kind: Service
metadata:
  name: nginx-api-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.210.5.24
  ports:
  - port: 8443
    targetPort: 8443
  selector:
    app: nginx-api-gateway
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-api-gateway
  labels:
    app: nginx-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-api-gateway
  template:
    metadata:
      labels:
        app: nginx-api-gateway
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-api-gateway-data
          mountPath: /etc/nginx/certs
        - name: nginx-api-gateway-content
          mountPath: /etc/nginx/html
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
      - name: nginx-api-gateway-data
        persistentVolumeClaim:
          claimName: nginx-api-gateway-data
      - name: nginx-api-gateway-content
        persistentVolumeClaim:
          claimName: nginx-api-gateway-content