apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webtest-config
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: webtest-config
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webtest-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: webtest-data
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webtest-log
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: webtest-log
  resources:
    requests:
      storage: 5Gi