apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: novatrackkeycloak-config
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: novatrackkeycloak-config
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: novatrackkeycloak-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: novatrackkeycloak-data
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: novatrackkeycloak-log
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: novatrackkeycloak-log
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: novatrackkeycloak-postgres-data-01
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi
  volumeName: novatrackkeycloak-postgres-data-01
  resources:
    requests:
      storage: 5Gi
