---
apiVersion: v1
kind: Service
metadata:
  name: redis
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
spec:
  selector:
    app: redis
  type: LoadBalancer
  loadBalancerIP: 10.210.5.96
  ports:
    - name: redis-tls
      port: 6379
      targetPort: 6379
    - name: redis-sentinel
      port: 26379
      targetPort: 26379
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
stringData:
  REDIS_PASSWORD: R@nd0m2025R@nd0m
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: redis
          image: bitnami/redis:8.0.2-debian-12-r4
          securityContext:
            runAsUser: 1001
          ports:
            - containerPort: 6379
              name: redis-tls
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
          command:
            - "sh"
            - "-c"
            - |
              redis-server \
                --tls-port 6379 \
                --port 0 \
                --tls-cert-file /certs/redis-fullchain.pem \
                --tls-key-file /certs/redis-privkey.pem \
                --tls-ca-cert-file /certs/redis-fullchain.pem \
                --requirepass "$REDIS_PASSWORD" \
                --masterauth "$REDIS_PASSWORD" \
                --appendonly yes \
                --cluster-enabled no \
                --bind 0.0.0.0 \
                --protected-mode no
          volumeMounts:
            - name: data
              mountPath: /bitnami/redis/data
            - name: keystore-volume-fullchain
              mountPath: /certs/redis-fullchain.pem
              subPath: "redis-fullchain.pem"
              readOnly: true
            - name: keystore-volume-privkey
              mountPath: /certs/redis-privkey.pem
              subPath: "redis-privkey.pem"
              readOnly: true
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 10
            periodSeconds: 10

        - name: sentinel
          image: bitnami/redis-sentinel:8.0.2-debian-12-r4
          ports:
            - containerPort: 26379
              name: redis-sentinel
          env:
            - name: REDIS_MASTER_HOST
              value: redis-0.redis.default.svc.cluster.local
            - name: REDIS_MASTER_PORT_NUMBER
              value: "6379"
            - name: REDIS_SENTINEL_QUORUM
              value: "2"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
          command:
            - "sh"
            - "-c"
            - |
              redis-sentinel /opt/bitnami/redis-sentinel/etc/sentinel.conf \
              --sentinel monitor mymaster "$REDIS_MASTER_HOST" "$REDIS_MASTER_PORT_NUMBER" 2 \
              --sentinel auth-pass mymaster "$REDIS_PASSWORD" \
              --sentinel down-after-milliseconds mymaster 10000 \
              --sentinel parallel-syncs mymaster 1 \
              --sentinel failover-timeout mymaster 180000
      volumes:
        - name: keystore-volume-fullchain
          secret:
            secretName: fullchain-redis-keystore
        - name: keystore-volume-privkey
          secret:
            secretName: privkey-redis-keystore
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: managed-csi
        resources:
          requests:
            storage: 5Gi
