apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
  - name: client
    port: 2181
    targetPort: 2181 
  - name: follower
    port: 2888
    targetPort: 2888 
  - name: leader
    port: 3888
    targetPort: 3888
  clusterIP: None    
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
spec:
  selector:
    statefulset.kubernetes.io/pod-name: kafka-kafka-0
    app: kafka
  ports:
  - port: 8444
    targetPort: 8444
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  replicas: 1
  serviceName: zookeeper
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        component: zookeeper
        app: zookeeper
    spec:
      volumes:
        - name: bitnami-data
          persistentVolumeClaim:
            claimName: bitnami-data
      containers:
      - name: zookeeper
        image: bitnami/zookeeper:latest
        securityContext:
          runAsUser: 0 
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        volumeMounts:
        - name: bitnami-data
          mountPath: /bitnami
        lifecycle:
          postStart:
            exec:
              command:
                - "sh"
                - "-c"
                - >
                  echo $(( $(cat /etc/hosts | grep zookeeper | awk '{print($3)}' | awk '{split($0,array,"-")} END{print array[3]}') + 1 )) > /bitnami/zookeeper/data/myid
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
        - name: ZOO_SERVERS
#          value:  zookeeper-0.zookeeper.default.svc.cluster.local:2888:3888,zookeeper-1.zookeeper.default.svc.cluster.local:2888:3888,zookeeper-2.zookeeper.default.svc.cluster.local:2888:3888
          value:  zookeeper-0.zookeeper.default.svc.cluster.local:2888:3888
      

---
apiVersion: apps/v1
kind: StatefulSet
#kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  serviceName: kafka
  selector:
    matchLabels:
        app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      hostname: kafka
      volumes:
        - name: bitnami-data
          persistentVolumeClaim:
            claimName: bitnami-data
      containers:
      - name: kafka
        image: bitnami/kafka:latest
        securityContext:
          runAsUser: 0
        resources:
          requests:
            memory: "1G"
            cpu: "1"             
        ports:
         - containerPort: 8444
        volumeMounts:
        - name: bitnami-data
          mountPath: /bitnami
        env:
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
#          value: zookeeper-0.zookeeper.default.svc.cluster.local:2181,zookeeper-1.zookeeper.default.svc.cluster.local:2181,zookeeper-2.zookeeper.default.svc.cluster.local:2181
#          value: zookeeper:2181
          value: zookeeper-0.zookeeper.default.svc.cluster.local:2181
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes" 
