apiVersion: v1
kind: Service
metadata:
  name: kafka
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
spec:
  type: ExternalName
  externalName: kafka.novusware.com.sg    
spec:
  selector:
    app: kafka
  ports:
  - name: internal-8444
    port: 8444
    targetPort: 9092
  - name: internal-9092
    port: 9092
    targetPort: 9092
  - name: external-8444
    port: 8444
    targetPort: 9092
  - name: external-9092
    port: 9092
    targetPort: 9092
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  replicas: 3
  serviceName: kafka
  selector:
    matchLabels:
        app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
      containers:
      - name: kafka
        image: bitnami/kafka:latest
        securityContext:
          runAsUser: 0
        resources:
          requests:
            memory: "1G"
            cpu: "1"             
        ports:
         - containerPort: 9092
        volumeMounts:
        - name: data
          mountPath: /bitnami
        env:
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
#          value: zookeeper-0.zookeeper-headless.default.svc.cluster.local:2181,zookeeper-1.zookeeper-headless.default.svc.cluster.local:2181,zookeeper-2.zookeeper-headless.default.svc.cluster.local:2181
          value: zookeeper.default.svc.cluster.local:2181
#          value: zookeeper-0.zookeeper.default.svc.cluster.local:2181
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_CFG_LISTENERS
          value: "PLAINTEXT://0.0.0.0:8444,EXTERNAL://0.0.0.0:8444"
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka.default.svc.cluster.local:8444,EXTERNAL://kafka.novusware.com.sg:8444"
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
        - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
          value: "PLAINTEXT"           
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "managed-csi"
      resources:
        requests:
          storage: 5Gi
