nfsServer: 10.0.0.25
containers:
  - name: bobagency
    database: bb_db_prd
    loadBalancerIP: 10.10.140.1
    port_1: 8443
    target_1: 8080
    req_cpu: 125m
    req_mem: 512Mi
    lim_cpu: 250m
    lim_mem: 1Gi
    type: maven
  - name: bobaudit
    database: au_db_prd
    loadBalancerIP: 10.10.140.2
    port_1: 8443
    target_1: 8080
    req_cpu: 125m
    req_mem: 512Mi
    lim_cpu: 250m
    lim_mem: 1024Mi
    type: maven
  - name: bobburs
    database: bur_db_prd
    loadBalancerIP: 10.10.140.3
    port_1: 8443
    target_1: 8080
    req_cpu: 125m
    req_mem: 512Mi
    lim_cpu: 250m
    lim_mem: 1024Mi
    type: maven
  - name: bobfileprocessing
    database: fp_db_prd
    loadBalancerIP: 10.10.140.4
    port_1: 8443
    target_1: 8080
    req_cpu: 125m
    req_mem: 256Mi
    lim_cpu: 250m
    lim_mem: 512Mi
    type: maven
  - name: boblogger
    database: bl_db_prd
    loadBalancerIP: 10.10.140.5
    port_1: 8443
    target_1: 8080
    req_cpu: 125m
    req_mem: 256Mi
    lim_cpu: 250m
    lim_mem: 512Mi
    type: maven
  - name: bobmessaging
    database: am_db_prd
    loadBalancerIP: 10.10.140.6
    port_1: 8443
    target_1: 8080
    req_cpu: 125m
    req_mem: 256Mi
    lim_cpu: 250m
    lim_mem: 1024Mi
    type: maven
  - name: bobmpos
    database: bobmpos_db_prd
    loadBalancerIP: 10.10.140.7
    port_1: 8443
    target_1: 8080
    req_cpu: 125m
    req_mem: 256Mi
    lim_cpu: 250m
    lim_mem: 1024Mi
    type: maven
  - name: bobmposinterface
    database: mi_db_prd
    loadBalancerIP: 10.10.140.8
    port_1: 8443
    target_1: 8080
    req_cpu: 125m
    req_mem: 256Mi
    lim_cpu: 250m
    lim_mem: 1024Mi
    type: maven
  - name: bobmposlogger
    database: bobmposlogger_db_prd
    loadBalancerIP: 10.10.140.9
    port_1: 8443
    target_1: 8080
    type: maven
    req_cpu: 125m
    req_mem: 256Mi
    lim_cpu: 250m
    lim_mem: 10242Mi
  - name: boboag
    database: og_db_prd
    loadBalancerIP: 10.10.140.10
    port_1: 8443
    target_1: 8080
    req_cpu: 125m
    req_mem: 256Mi
    lim_cpu: 250m
    lim_mem: 1024Mi
    type: maven
  - name: bobonegov
    database: ogo_db_prd
    loadBalancerIP: 10.10.140.11
    port_1: 8443
    target_1: 8080
    req_cpu: 125m
    req_mem: 512Mi
    lim_cpu: 250m
    lim_mem: 1Gi
    type: maven
  - name: bobpayment
    database: ps_db_prd
    loadBalancerIP: 10.10.140.12
    port_1: 8443
    target_1: 8080
    req_cpu: 125m
    req_mem: 256Mi
    lim_cpu: 250m
    lim_mem: 1024Mi
    type: maven
  - name: bobqueuemanager
    database: qm_db_prd
    loadBalancerIP: 10.10.140.13
    port_1: 8443
    target_1: 8080
    req_cpu: 125m
    req_mem: 256Mi
    lim_cpu: 250m
    lim_mem: 1024Mi
    type: maven
  - name: bobreferencing
    database: rf_db_prd
    loadBalancerIP: 10.10.140.14
    port_1: 8443
    target_1: 8080
    req_cpu: 125m
    req_mem: 256Mi
    lim_cpu: 250m
    lim_mem: 1024Mi
    type: maven
  - name: bobreporting
    database: rp_db_prd
    loadBalancerIP: 10.10.14015
    port_1: 8443
    target_1: 8080
    req_cpu: 125m
    req_mem: 512Mi
    lim_cpu: 250m
    lim_mem: 1Gi
    type: maven
#  - name: bobswitchinterface
#    database: sw_db_prd
#    loadBalancerIP: 10.10.140.16
#    port_1: 8175
#    target_1: 8080
#    port_2: 6666
#    target_2: 6666
#    type: maven
  - name: boburm
    database: urm_db_prd
    loadBalancerIP: 10.10.140.17
    port_1: 8443
    target_1: 8080
    req_cpu: 125m
    req_mem: 256Mi
    lim_cpu: 250m
    lim_mem: 1024Mi
    type: maven
  - name: bobuserlimits
    database: ul_db_prd
    loadBalancerIP: 10.10.140.18
    port_1: 8443
    target_1: 8080
    req_cpu: 125m
    req_mem: 256Mi
    lim_cpu: 250m
    lim_mem: 1024Mi
    type: maven
  - name: bobmerchantmate
    database: bobmerchantmate_db_prd
    loadBalancerIP: 10.10.140.28
    port_1: 8443
    target_1: 8080
    req_cpu: 125m
    req_mem: 256Mi
    lim_cpu: 250m
    lim_mem: 1024Mi
    type: maven
  - name: bobnovatrackintapp
    database: bobnovatrack_db_prd
    loadBalancerIP: 10.10.140.31
    port_1: 8443
    target_1: 8080
    req_cpu: 125m
    req_mem: 256Mi
    lim_cpu: 250m
    lim_mem: 1024Mi
    type: maven
  - name: bobnovatrackextapp
    database: bobnovatrack_db_prd
    loadBalancerIP: 10.10.140.29
    port_1: 8443
    target_1: 8080
    req_cpu: 125m
    req_mem: 256Mi
    lim_cpu: 250m
    lim_mem: 1024Mi
    type: maven
  - name: bobcoindeposit
    database: cs_db_prd
    loadBalancerIP: 10.10.140.27
    port_1: 8443
    target_1: 8080
    req_cpu: 125m
    req_mem: 256Mi
    lim_cpu: 250m
    lim_mem: 1024Mi
    type: maven    
  - name: bobr3portal
    loadBalancerIP: 10.10.140.19
    port_1: 8443
    target_1: 3006
    req_cpu: 125m
    req_mem: 256Mi
    lim_cpu: 250m
    lim_mem: 512Mi
    type: react
  - name: bobsignage
    loadBalancerIP: 10.10.140.20
    port_1: 8443
    target_1: 3008
    req_cpu: 125m
    req_mem: 256Mi
    lim_cpu: 250m
    lim_mem: 512Mi
    type: react
  - name: bobnovatrackintportal
    loadBalancerIP: 10.10.140.32
    port_1: 8443
    target_1: 3005
    req_cpu: 125m
    req_mem: 256Mi
    lim_cpu: 250m
    lim_mem: 512Mi
    type: react
  - name: bobnovatrackextportal
    loadBalancerIP: 10.10.140.30
    port_1: 8443
    target_1: 3007
    req_cpu: 125m
    req_mem: 256Mi
    lim_cpu: 250m
    lim_mem: 512Mi
    type: react
  - name: bobburssimulator
    loadBalancerIP: 10.10.140.34
    port_1: 8443
    target_1: 3009
    req_cpu: 125m
    req_mem: 256Mi
    lim_cpu: 250m
    lim_mem: 512Mi
    type: react
