apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.yaml: |
    spring:
      cache:
        type: redis
        redis:
          time-to-live: 5m
      data:
        redis:
          port: 6379
          host: redis.novusware.com.sg
          ssl: true          
          password: ${REDIS_PASSWORD}
