# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

resources:
 repositories:
   - repository: bobr3portal
     type: git
     name: 'BOB - Digital Revenue Collection System/bobr3portal'
     ref: refs/heads/release
   - repository: bobsignage
     type: git
     name: 'BOB - Digital Revenue Collection System/bobsignage'
     ref: refs/heads/release

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'db9b844b-fbd5-4c4b-9e0f-41e21cd3087f'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build_bobr3portal
    displayName: Build bobR3portal
    pool:
      vmImage: $(vmImageName)
    steps:
    - checkout: bobR3portal
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: 'bobr3portal'
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          latest
          $(Build.BuildId)
  - job: Build_bobsignage
    displayName: Build bobsignage
    pool:
      vmImage: $(vmImageName)
    steps:
    - checkout: bobsignage
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: 'bobsignage'
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          latest
          $(Build.BuildId)