# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

resources:
 repositories:
   - repository: bobr3portal
     type: git
     name: 'BOB - Digital Revenue Collection System/bobr3portal'
   - repository: bobsignage
     type: git
     name: 'BOB - Digital Revenue Collection System/bobsignage'
   - repository: bobnovatrackintportal
     type: git
     name: 'BOB - Digital Revenue Collection System/bobnovatrackintportal'
   - repository: bobnovatrackextportal
     type: git
     name: 'BOB - Digital Revenue Collection System/bobnovatrackextportal'
   - repository: bobburssimulator
     type: git
     name: 'BOB - Digital Revenue Collection System/bobburssimulator'

variables:
  - name: dockerfilePath
    value: '$(Build.SourcesDirectory)/Dockerfile'
  - name: tag
    value: '$(Build.BuildId)'
  - name: vmImageName
    value: 'ubuntu-latest'
  - name: environmentName
    value: 'uat' 
  - group: build-variables        

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build_bobr3portal
    displayName: Build bobR3portal
    pool:
      vmImage: $(vmImageName)
    steps:
    - checkout: bobR3portal
    - script: |
        cp $(Build.SourcesDirectory)/.env.$(environmentName) $(Build.SourcesDirectory)/.env
      displayName: "Use environment-specific .env"    
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: 'bobr3portal'
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          latest
          $(Build.BuildId)
  - job: Build_bobsignage
    displayName: Build bobsignage
    pool:
      vmImage: $(vmImageName)
    steps:
    - checkout: bobsignage
    - script: |
        cp $(Build.SourcesDirectory)/.env.$(environmentName) $(Build.SourcesDirectory)/.env
      displayName: "Use environment-specific .env"    
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: 'bobsignage'
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          latest
          $(Build.BuildId)
    - task: Docker@2
      displayName: Build and push an image to container registry 2
      inputs:
        command: buildAndPush
        repository: 'bobsignage'
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection2)
        tags: |
          latest
          $(Build.BuildId)

  - job: Build_bobnovatrackintportal
    displayName: Build bobnovatrackintportal
    pool:
      vmImage: $(vmImageName)
    steps:
    - checkout: bobnovatrackintportal
    - script: |
        cp $(Build.SourcesDirectory)/.env.$(environmentName) $(Build.SourcesDirectory)/.env
      displayName: "Use environment-specific .env"    
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: 'bobnovatrackintportal'
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          latest
          $(Build.BuildId)
    - task: Docker@2
      displayName: Build and push an image to container registry 2
      inputs:
        command: buildAndPush
        repository: 'bobnovatrackintportal'
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection2)
        tags: |
          latest
          $(Build.BuildId)

  - job: Build_bobnovatrackextportal
    displayName: Build bobnovatrackextportal
    pool:
      vmImage: $(vmImageName)
    steps:
    - checkout: bobnovatrackextportal
    - script: |
        cp $(Build.SourcesDirectory)/.env.$(environmentName) $(Build.SourcesDirectory)/.env
      displayName: "Use environment-specific .env"    
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: 'bobnovatrackextportal'
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          latest
          $(Build.BuildId)  
    - task: Docker@2
      displayName: Build and push an image to container registry 2
      inputs:
        command: buildAndPush
        repository: 'bobnovatrackextportal'
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection2)
        tags: |
          latest
          $(Build.BuildId)  

  - job: Build_bobburssimulator
    displayName: Build bobburssimulator
    pool:
      vmImage: $(vmImageName)
    steps:
    - checkout: bobburssimulator
    - script: |
        cp $(Build.SourcesDirectory)/.env.$(environmentName) $(Build.SourcesDirectory)/.env
      displayName: "Use environment-specific .env"    
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: 'bobburssimulator'
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          latest
          $(Build.BuildId)              
    - task: Docker@2
      displayName: Build and push an image to container registry 2
      inputs:
        command: buildAndPush
        repository: 'bobburssimulator'
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection2)
        tags: |
          latest
          $(Build.BuildId)                        