containers:
  - name: bobagency
    database: bb_db_dev
    loadBalancerIP: 10.210.5.27
    port_1: 8130
    target_1: 8080
    type: maven
  - name: bobaudit
    database: au_db_dev
    loadBalancerIP: 10.210.5.33
    port_1: 8120
    target_1: 8080
    type: maven
  - name: bobburs
    database: bur_db_dev
    loadBalancerIP: 10.210.5.38
    port_1: 8145
    target_1: 8080
    type: maven
  - name: bobfileprocessing
    database: fp_db_dev
    loadBalancerIP: 10.210.5.38
    port_1: 8140
    target_1: 8080
    type: maven
  - name: boblogger
    database: bl_db_dev
    loadBalancerIP: 10.210.5.14
    port_1: 80
    target_1: 8080
    type: maven
  - name: bobmessaging
    database: am_db_dev
    loadBalancerIP: 10.210.5.28
    port_1: 8115
    target_1: 8080
    type: maven
  - name: bobmpos
    database: mpos_db_dev
    loadBalancerIP: 10.210.5.38
    port_1: 8120
    target_1: 8080
    type: maven
  - name: bobmposinterface
    database: mi_db_dev
    loadBalancerIP: 10.210.5.15
    port_1: 8155
    target_1: 8080
    type: maven
  - name: bobmposlogger
    database: mposlogger_db_dev
    loadBalancerIP: 10.210.5.39
    port_1: 8150
    target_1: 8080
    type: maven
  - name: boboag
    database: og_db_dev
    loadBalancerIP: 10.210.5.16
    port_1: 8135
    target_1: 8080
    type: maven
  - name: bobonegov
    database: ogo_db_dev
    loadBalancerIP: 10.210.5.17
    port_1: 8170
    target_1: 8080
    type: maven
  - name: bobpayment
    database: ps_db_dev
    loadBalancerIP: 10.210.5.18
    port_1: 8125
    target_1: 8080
    type: maven
  - name: bobqueuemanager
    database: qm_db_dev
    loadBalancerIP: 10.210.5.19
    port_1: 8100
    target_1: 8080
    type: maven
  - name: bobreferencing
    database: rf_db_dev
    loadBalancerIP: 10.210.5.20
    port_1: 8095
    target_1: 8080
    type: maven
  - name: bobreporting
    database: rp_db_dev
    loadBalancerIP: 10.210.5.21
    port_1: 8160
    target_1: 8080
    type: maven
#  - name: bobswitchinterface
#    database: sw_db_dev
#    loadBalancerIP: 10.210.5.36
#    port_1: 8175
#    target_1: 8080
#    port_2: 6666
#    target_2: 6666
#    type: maven
  - name: boburm
    database: urm_db_dev
    loadBalancerIP: 10.210.5.30
    port_1: 8110
    target_1: 8080
    type: maven
  - name: bobuserlimits
    database: ul_db_dev
    loadBalancerIP: 10.210.5.31
    port_1: 8165
    target_1: 8080
    type: maven
  - name: bobr3portal
    loadBalancerIP: 10.210.5.25
    port_1: 3006
    target_1: 3006
    type: react
  - name: bobsignage
    loadBalancerIP: 10.210.5.37
    port_1: 3008
    target_1: 3008
    type: react
