containers:
  - name: bobagency
  - name: bobauditservice
  - name: bobburs
  - name: bobagency
  - name: bobauditservice
  - name: bobburs
  - name: bobfileprocessing
  - name: boblogger
  - name: bobmessaging
  - name: bobmpos
  - name: bobmposinterface
  - name: bobmposlogger
  - name: boboag
  - name: bobonegov
  - name: bobpaymentapi
  - name: bobqueuemanager
  - name: bobr3portal
  - name: bobreferencing
  - name: bobreporting
  - name: bobsignage
  - name: bobswitchinterface
  - name: boburm
  - name: bobuserlimits