{{- range .Values.containers }}
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
  name: {{ .name }}-log
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi
  csi:
    driver: file.csi.azure.com
    volumeHandle: {{ .name }}-log-01
    volumeAttributes:
      resourceGroup: rg-dcrs-uat-01
      shareName: {{ .name }}-log
    nodeStageSecretRef:
      name: n0vdcrsuat03
      namespace: default
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict
    - nosharesock
    - actimeo=30
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}-log
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: {{ .name }}-log
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
  name: {{ .name }}-data
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi
  csi:
    driver: file.csi.azure.com
    volumeHandle: {{ .name }}-data-01
    volumeAttributes:
      resourceGroup: rg-dcrs-data-01
      shareName: {{ .name }}-data
    nodeStageSecretRef:
      name: n0vdcrsuat02
      namespace: default
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict
    - nosharesock
    - actimeo=30
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: {{ .name }}-data
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
  name: {{ .name }}-config
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi
  csi:
    driver: file.csi.azure.com
    volumeHandle: {{ .name }}-config-01
    volumeAttributes:
      resourceGroup: rg-dcrs-config-01
      shareName: {{ .name }}-config
    nodeStageSecretRef:
      name: n0vdcrsuat01
      namespace: default
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict
    - nosharesock
    - actimeo=30
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}-config
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: {{ .name }}-config
  resources:
    requests:
      storage: 5Gi
{{- end }}
