apiVersion: v1
kind: Service
metadata:
  name: nginx-api-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.207.10.146
  ports:
  - port: 8443
    targetPort: 8443
  selector:
    app: nginx-api-gateway
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-api-gateway
  labels:
    app: nginx-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-api-gateway
  template:
    metadata:
      labels:
        app: nginx-api-gateway
    spec:
      containers:
      - name: nginx
        image: nginx:1.29.0
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: keystore-volume-fullchain
          mountPath: "/etc/nginx/certs/uat.novaware-fullchain.pem"
          subPath: "uat.novaware-fullchain.pem"
          readOnly: true 
        - name: keystore-volume-privkey
          mountPath: "/etc/nginx/certs/uat.novaware-privkey.pem"
          subPath: "uat.novaware-privkey.pem"
          readOnly: true 
        - name: nginx-api-gateway-content
          mountPath: /etc/nginx/html
          subPath: "nginx-api-gateway"
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
      - name: nginx-api-gateway-content
        persistentVolumeClaim:
          claimName: nginx-api-gateway-content
      - name: keystore-volume-fullchain
        secret:
          secretName: fullchain-uat.novaware-keystore
      - name: keystore-volume-privkey
        secret:
          secretName: privkey-uat.novaware-keystore




