apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-redis-0
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi
  volumeName: redis-0
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-redis-1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi
  volumeName: redis-1
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-redis-2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi
  volumeName: redis-2
  resources:
    requests:
      storage: 5Gi
