apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-zookeeper-0
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: zookeeper-0
  resources:
    requests:
      storage: 16Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-zookeeper-1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: zookeeper-1
  resources:
    requests:
      storage: 16Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-zookeeper-2
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: zookeeper-2
  resources:
    requests:
      storage: 16Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-kafka
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: kafka
  resources:
    requests:
      storage: 16Gi
