apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-config
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: postgres-config
  resources:
    requests:
      storage: 16Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: postgres-data
  resources:
    requests:
      storage: 16Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-log
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: postgres-log
  resources:
    requests:
      storage: 16Gi
