apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel
spec:
  selector:
    app: redis-sentinel
  ports:
    - name: sentinel
      port: 26379
      targetPort: 26379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-sentinel
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis-sentinel
  template:
    metadata:
      labels:
        app: redis-sentinel
    spec:
      containers:
        - name: sentinel
          image: bitnami/redis:8.0.2-debian-12-r4
          command:
            - sh
            - -c
            - |
              echo "[Sentinel] Waiting for redis-0.redis.default.svc.cluster.local to resolve..."
              until getent hosts redis-0.redis.default.svc.cluster.local; do sleep 2; done

              cat <<EOF > /tmp/sentinel.conf
              sentinel monitor mymaster redis-0.redis.default.svc.cluster.local 6380 2
              sentinel auth-pass mymaster $REDIS_PASSWORD
              sentinel down-after-milliseconds mymaster 5000
              sentinel failover-timeout mymaster 10000
              EOF

              echo "[Sentinel] Starting with:"
              cat /tmp/sentinel.conf

              redis-sentinel /tmp/sentinel.conf
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
          ports:
            - containerPort: 26379
              name: sentinel