apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
spec:
  clusterIP: None
  selector:
    app: kafka
  ports:
    - name: internal
      port: 8444
      targetPort: 8444
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka-headless
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:latest
          securityContext:
            runAsUser: 0
          resources:
            requests:
              memory: "1G"
              cpu: "1"
          ports:
            - containerPort: 8444
            - containerPort: 9092
          env:
            - name: KAFKA_HEAP_OPTS
              value: "-Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true"
            # ADD THIS ENVIRONMENT VARIABLE:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper.default.svc.cluster.local:2181
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_LISTENERS
              value: "INTERNAL://0.0.0.0:8444,EXTERNAL://0.0.0.0:9092"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INTERNAL://kafka-0.kafka-headless.default.svc.cluster.local:8444,EXTERNAL://kafka-0.kafka.uat.novaware.com.sg:9092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
          volumeMounts:
            - name: data
              mountPath: /var/lib/kafka
  volumeClaimTemplates:
    - metadata:
      name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: 'true' # Set to 'false' for an EXTERNAL LoadBalancer
spec:
  selector:
    app: kafka
  type: LoadBalancer
  loadBalancerIP: 10.207.10.102 # Your desired IP address (internal or external)
  ports:
    - name: internal
      port: 8444
      targetPort: 8444
    - name: external
      port: 9092
      targetPort: 9092