apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
spec:
  clusterIP: None
  selector:
    app: kafka
  ports:
    - name: internal
      port: 8444
      targetPort: 8444
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka-headless
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:3.9.0
          ports:
            - containerPort: 8444
          volumeMounts:
            - name: data
              mountPath: /bitnami
              subPathExpr: "$(POD_NAME)"
          env:
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: zookeeper.default.svc.cluster.local:2181
            - name: KAFKA_CFG_LISTENERS
              value: PLAINTEXT://0.0.0.0:8444
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: PLAINTEXT://$(POD_NAME).kafka-headless.default.svc.cluster.local:8444
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT
            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-proxy
  template:
    metadata:
      labels:
        app: kafka-proxy
    spec:
      containers:
        - name: kafka-proxy
          image: grepplabs/kafka-proxy:latest
          args:
            - server
            - --bootstrap-server-mapping=kafka-0.kafka-headless.default.svc.cluster.local:8444,0.0.0.0:9092,kafka.uat.novaware.com.sg:9092
            - --bootstrap-server-mapping=kafka-1.kafka-headless.default.svc.cluster.local:8444,0.0.0.0:9092,kafka.uat.novaware.com.sg:9092
            - --bootstrap-server-mapping=kafka-2.kafka-headless.default.svc.cluster.local:8444,0.0.0.0:9092,kafka.uat.novaware.com.sg:9092
          ports:
            - containerPort: 19092
---  
apiVersion: v1
kind: Service
metadata:
  name: kafka-proxy
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
spec:
  selector:
    app: kafka-proxy
  type: LoadBalancer
  loadBalancerIP: 10.207.10.102
  ports:
    - name: kafka
      port: 9092
      targetPort: 19092

