apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: default
  labels:
    app: redis
data:
  redis-config.yaml: |
    spring:
      cache:
        type: redis
        redis:
          time-to-live: 5m
      data:
        redis:
          port: 6379
          host: redis.novusware.com.sg
          password: ${REDIS_PASSWORD}

