apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace:prd
data:
  redis.yaml: |
    spring:
      cache:
        type: redis
        redis:
          time-to-live: 5m
      data:
        redis:
          port: 6379
          host: redis-prd-service.bh.bob.bw
          password: ${REDIS_PASSWORD}
