apiVersion: v1
kind: ConfigMap
metadata:
  name: url-config
data:
  url.yaml: |
    url:
      am:
        sendSms: https://bobmessaging-prd-service.bh.bob.bw:8443/am/sendSms
        sendEmail: https://bobmessaging-prd-service.bh.bob.bw:8443/am/sendEmail
        sendEmailAndSms: https://bobmessaging-prd-service.bh.bob.bw:8443/am/sendEmailAndSms
        sendHtmlEmail: https://bobmessaging-prd-service.bh.bob.bw:8443/am/sendHtmlEmail
        sendHtmlEmailAndSms: https://bobmessaging-prd-service.bh.bob.bw:8443/am/sendHtmlEmailAndSms
        sendHtmlEmailWithReceipt: https://bobmessaging-prd-service.bh.bob.bw:8443/am/sendHtmlEmailWithReceipt
      au:
        getAuditLogs : https://bobaudit-prd-service.bh.bob.bw:8443/audit/getAuditLogs
        getAuditLogsWithPagination: https://bobaudit-prd-service.bh.bob.bw:8443/audit/getAuditLogsWithPagination
      ui:
        forceChangePwdUrl: https://portal.drcs.bh.bob.bw/drcs-force-change-password
        changePwdPage: drcs-force-change-password
      bb:
        bankingHallTransactionNotification: https://bobagency-prd-service.bh.bob.bw:8443/bob/bankingHallTransactionNotification
        fetchSwiftDataIfForeignRequest: https://bobagency-prd-service.bh.bob.bw:8443/bob/fetchSwiftDataIfForeignRequest
        getAgencyLocations: https://bobagency-prd-service.bh.bob.bw:8443/bob/getAgencyLocations
        getAllAgencyCode: https://bobagency-prd-service.bh.bob.bw:8443/bob/getAllAgencyCode
        getAllLocation: https://bobagency-prd-service.bh.bob.bw:8443/master/getAllLocation
        getAllRevenueCodeGroup: https://bobagency-prd-service.bh.bob.bw:8443/master/getAllRevenueCodeGroup
        getAllRevenueCodeByRevenueCodeGroupIdList: https://bobagency-prd-service.bh.bob.bw:8443/master/getAllRevenueCodeByRevenueCodeGroupIdList
        getAllSubAgencyCode: https://bobagency-prd-service.bh.bob.bw:8443/bob/getSubAgencyCode        
        getAllTransactionTypes: https://bobagency-prd-service.bh.bob.bw:8443/master/getAllTransactionTypes
        getAppConfigs: https://bobagency-prd-service.bh.bob.bw:8443/master/getAppConfigs
        getCbsAccountDetails: https://bobagency-prd-service.bh.bob.bw:8443/master/getCbsAccountDetails
        getCommercialBankByBankId: https://bobagency-prd-service.bh.bob.bw:8443/bob/getCommercialBankByBankId
        getCustomerContact: https://bobagency-prd-service.bh.bob.bw:8443/bob/getCustomerContact
        getLocation: https://bobagency-prd-service.bh.bob.bw:8443/master/getLocation
        getParentCommercialBankCode: https://bobagency-prd-service.bh.bob.bw:8443/bob/getParentCommercialBankCode
        getRevenueCodeByRevenueCode: https://bobagency-prd-service.bh.bob.bw:8443/master/getRevenueCodeByRevenueCode
        processReversalTransaction: https://bobagency-prd-service.bh.bob.bw:8443/bob/processReversalTransaction
        validateApiRequest: https://bobagency-prd-service.bh.bob.bw:8443/bob/validateApiRequest
        validateImportUserList: https://bobagency-prd-service.bh.bob.bw:8443/bob/validateImportUserList        
        validateMerchantSecret: https://bobagency-prd-service.bh.bob.bw:8443/master/validateMerchantSecret        
        validateStagingReference: https://bobagency-prd-service.bh.bob.bw:8443/bob/validateStagingReference
      br:
        updateUserLimitForReversal: https://bobburs-prd-service.bh.bob.bw:8443/br/updateUserLimitForReversal        
      rf:
        generateS3: https://bobreferencing-prd-service.bh.bob.bw:8443/staging/generateS3
        generateUrn: https://bobreferencing-prd-service.bh.bob.bw:8443/referencing/generateUrn
      og:
        updateUserLimitForReversal: https://boboag-prd-service.bh.bob.bw:8443/oag/updateUserLimitForReversal        
      ps:
        assignConsolidation: https://bobpayment-prd-service.bh.bob.bw:8443/ps/assignConsolidation
        cancelWithdrawalReference: https://bobpayment-prd-service.bh.bob.bw:8443/ps/cancelWithdrawalReference
        dashBoardVlnBdleNotDeposit: https://bobpayment-prd-service.bh.bob.bw:8443/ps/getDshBrdViolationOfBdleNotDeposit
        deleteBankingHallDepositAmount: https://bobpayment-prd-service.bh.bob.bw:8443/ps/deleteBankingHallDepositAmount
        deleteBankingHallTransaction: https://bobpayment-prd-service.bh.bob.bw:8443/ps/deleteBankingHallTransaction
        expireWithdrawalReference: https://bobpayment-prd-service.bh.bob.bw:8443/ps/expireWithdrawalReference
        getAllPartialStagingByStagedRefNum: https://bobpayment-prd-service.bh.bob.bw:8443/ps/getAllPartialStagingByStagedRefNum
        getBankingHallDepositAmount: https://bobpayment-prd-service.bh.bob.bw:8443/ps/getBankingHallDepositAmount
        getBankingHallDepositTransactions: https://bobpayment-prd-service.bh.bob.bw:8443/ps/getBankingHallDepositTransactions
        getBankingHallTransaction: https://bobpayment-prd-service.bh.bob.bw:8443/ps/getBankingHallTransaction
        getBhTransactionsJourney: https://bobpayment-prd-service.bh.bob.bw:8443/ps/getBhTransactionsJourney
        getBundleTransactions: https://bobpayment-prd-service.bh.bob.bw:8443/ps/getBundleTransactions
        getCommercialBankUserTransactions: https://bobpayment-prd-service.bh.bob.bw:8443/ps/getCommercialBankUserTransactions
        getCollectionTransactions: https://bobpayment-prd-service.bh.bob.bw:8443/ps/getCollectionTransactions
        getConsoliadtionTransactions: https://bobpayment-prd-service.bh.bob.bw:8443/ps/getConsoliadtionTransactions
        getDashboardBobDistOverview: https://bobpayment-prd-service.bh.bob.bw:8443/ps/getDashboardBobDistOverview
        getDashboardCashMovement: https://bobpayment-prd-service.bh.bob.bw:8443/ps/getDashboardCashMovement
        getDshBoardRevenueCollDetailedView: https://bobpayment-prd-service.bh.bob.bw:8443/ps/getDshBoardRevenueCollDetailedView
        getListOfPaymentForComBankTxn: https://bobpayment-prd-service.bh.bob.bw:8443/ps/getListOfPaymentForComBankTxn
        getListOfPaymentForStaging: https://bobpayment-prd-service.bh.bob.bw:8443/ps/getListOfPaymentForStaging
        getNextStage: https://bobpayment-prd-service.bh.bob.bw:8443/ps/getNextStage        
        getPOSCollectionSummary: https://bobpayment-prd-service.bh.bob.bw:8443/ps/getPOSCollectionSummary
        getPreviousStage: https://bobpayment-prd-service.bh.bob.bw:8443/ps/getPreviousStage
        getPartialStagingJourney: https://bobpayment-prd-service.bh.bob.bw:8443/ps/getPartialStagingJourney
        getReceipt: https://bobpayment-prd-service.bh.bob.bw:8443/ps/getReceipt
        getSplitAmountForWithdrawal: https://bobpayment-prd-service.bh.bob.bw:8443/ps/getSplitAmountForWithdrawal
        getStagedTransaction: https://bobpayment-prd-service.bh.bob.bw:8443/ps/getStagedTransaction
        getStagingDetails: https://bobpayment-prd-service.bh.bob.bw:8443/ps/getStagingDetails
        getStagingDetailWithHistory: https://bobpayment-prd-service.bh.bob.bw:8443/ps/getStagingDetailWithHistory
        getStagingSummary: https://bobpayment-prd-service.bh.bob.bw:8443/ps/getStagingSummary
        getTodayTransactionAmount: https://bobpayment-prd-service.bh.bob.bw:8443/ps/getTodayTransactionAmount
        getURNHistory: https://bobpayment-prd-service.bh.bob.bw:8443/ps/getURNHistory
        getUrnSummary: https://bobpayment-prd-service.bh.bob.bw:8443/ps/getUrnSummary
        getUrnTransactions: https://bobpayment-prd-service.bh.bob.bw:8443/ps/getUrnTransactions
        getUserTransactions: https://bobpayment-prd-service.bh.bob.bw:8443/ps/getUserTransactions
        processReversalTransaction: https://bobpayment-prd-service.bh.bob.bw:8443/ps/processReversalTransaction
        processRfPayment: https://bobpayment-prd-service.bh.bob.bw:8443/ps/processRfPayment
        reconcileCardPayment: https://bobpayment-prd-service.bh.bob.bw:8443/ps/reconcileCardPayment
        saveBankingHallDepositAmount: https://bobpayment-prd-service.bh.bob.bw:8443/ps/saveBankingHallDepositAmount
        saveBankingHallTransaction: https://bobpayment-prd-service.bh.bob.bw:8443/ps/saveBankingHallTransaction
        searchS3: https://bobpayment-prd-service.bh.bob.bw:8443/ps/searchS3
        searchS3FutureResult: https://bobpayment-prd-service.bh.bob.bw:8443/ps/searchS3FutureResult
        searchS3History: https://bobpayment-prd-service.bh.bob.bw:8443/ps/searchS3History
        updateBankingHallTransaction: https://bobpayment-prd-service.bh.bob.bw:8443/ps/updateBankingHallTransaction
        updateBankingHallTxn: https://bobpayment-prd-service.bh.bob.bw:8443/ps/updateBankingHallTxn
        updateComBankTxnValidation: https://bobpayment-prd-service.bh.bob.bw:8443/ps/updateComBankTxnValidation
        updateStagingValidation: https://bobpayment-prd-service.bh.bob.bw:8443/ps/updateStagingValidation
        urnSearch: https://bobpayment-prd-service.bh.bob.bw:8443/ps/urnSearch
        validateComBankTxn: https://bobpayment-prd-service.bh.bob.bw:8443/ps/validateComBankTxn
        validateStagingDataForUser: https://bobpayment-prd-service.bh.bob.bw:8443/ps/validateStagingDataForUser
        validateBankingHallDepositAmount: https://bobpayment-prd-service.bh.bob.bw:8443/ps/validateBankingHallDepositAmount
        validateBankingHallTransaction: https://bobpayment-prd-service.bh.bob.bw:8443/ps/validateBankingHallTransaction
        validateExcessWithdrawalRefNum: https://bobpayment-prd-service.bh.bob.bw:8443/ps/validateExcessWithdrawalRefNum
        withdrawExcessAmount: https://bobpayment-prd-service.bh.bob.bw:8443/ps/withdrawExcessAmount
      qm:
        changebusystatusTerminal: https://bobqueuemanager-prd-service.bh.bob.bw:8443/queue/changebusystatusTerminal
        changeOperatingstatusTerminal: https://bobqueuemanager-prd-service.bh.bob.bw:8443/queue/changeOperatingstatusTerminal
        validateQueueDetails: https://bobqueuemanager-prd-service.bh.bob.bw:8443/queue/validateQueueDetails
        terminalfreeNotification: https://bobqueuemanager-prd-service.bh.bob.bw:8443/queue/terminalfreeNotification
        updateQueueStatus: https://bobqueuemanager-prd-service.bh.bob.bw:8443/queue/updateQueueStatus
      sw:
        processUpdateT24: https://bobswitchinterface-prd-service.bh.bob.bw:8443/processUpdateT24
        generateOtp: https://bobswitchinterface-prd-service.bh.bob.bw:8443/sw/generateOtp
        processS3ValidationRequest: https://bobswitchinterface-prd-service.bh.bob.bw:8443/processS3ValidationRequest
        processTxnNotificationRequest: https://bobswitchinterface-prd-service.bh.bob.bw:8443/processTxnNotificationRequest
      ul:
        deleteLimits: https://bobuserlimits-prd-service.bh.bob.bw:8443/limits/deleteLimits
        depositAmt: https://bobuserlimits-prd-service.bh.bob.bw:8443/limits/depositAmt
        getAllViolationDetails: https://bobuserlimits-prd-service.bh.bob.bw:8443/limits/getAllViolationDetails
        getLimits: https://bobuserlimits-prd-service.bh.bob.bw:8443/limits/getLimits
        insertStageTracking: https://bobuserlimits-prd-service.bh.bob.bw:8443/limits/insertStageTracking
        insertLimits: https://bobuserlimits-prd-service.bh.bob.bw:8443/limits/insertLimits
        revertUserLimit: https://bobuserlimits-prd-service.bh.bob.bw:8443/limits/revertUserLimit
        updateLimits: https://bobuserlimits-prd-service.bh.bob.bw:8443/limits/updateLimits
        updateBulkUserLimits: https://bobuserlimits-prd-service.bh.bob.bw:8443/limits/updateBulkUserLimits
        updateUserLimitForReversal: https://bobuserlimits-prd-service.bh.bob.bw:8443/limits/updateUserLimitForReversal
        validateUserLimit: https://bobuserlimits-prd-service.bh.bob.bw:8443/limits/validateUserLimit
      um:
        addUserNotification: https://boburm-prd-service.bh.bob.bw:8443/notification/addUserNotification      
        getAgencyWiseParentMid: https://boburm-prd-service.bh.bob.bw:8443/urm/getAgencyWiseParentMid
        getAllIdentityType:  https://boburm-prd-service.bh.bob.bw:8443/idType/getAllIdentityType
        getUser: https://boburm-prd-service.bh.bob.bw:8443/urm/getUser
        getUserDetailsByPermissionId: https://boburm-prd-service.bh.bob.bw:8443/urm/getUserDetailsByPermissionId
        hasPermissionForRole: https://boburm-prd-service.bh.bob.bw:8443/authentication/hasPermissionForRole
        removeRevenueCodeGroup: https://boburm-prd-service.bh.bob.bw:8443/user/removeRevenueCodeGroup
        view: https://boburm-prd-service.bh.bob.bw:8443/user/view
      extapp:
        createUser: https://bobnovatrackextapp-prd-service.bh.bob.bw:8443/bobnovatrack/nova/merchant/createURM
        savemerchant: https://bobnovatrackextapp-prd-service.bh.bob.bw:8443/bobnovatrack/nova/merchant/save
        setTerminalPwd: https://bobnovatrackextapp-prd-service.bh.bob.bw:8443/bobnovatrack/nova/merchant/setTerminalPswdInt
        changeTerminalPwd: https://bobnovatrackextapp-prd-service.bh.bob.bw:8443/bobnovatrack/nova/merchant/changeTerminalPswdInt
        resetTerminalPwd: https://bobnovatrackextapp-prd-service.bh.bob.bw:8443/bobnovatrack/nova/merchant/resetTerminalPswdInt
        changeMidStatus: https://bobnovatrackextapp-prd-service.bh.bob.bw:8443/bobnovatrack/nova/merchant/updateUserStatus
        viewMerchantStatus: https://bobnovatrackextapp-prd-service.bh.bob.bw:8443/bobnovatrack/nova/merchant/viewStatus
        disputeAttchment: https://bobnovatrackextapp-prd-service.bh.bob.bw:8443/bobnovatrack/mportal/chargeback/downloadFile
        serviceAttchment: https://bobnovatrackextapp-prd-service.bh.bob.bw:8443/bobnovatrack/mportal/request/downloadFile
      extApp:
        changeMidStatus: https://bobnovatrackextapp-prd-service.bh.bob.bw:8443/bobnovatrack/nova/merchant/updateUserStatus
        changeTerminalPwd: https://bobnovatrackextapp-prd-service.bh.bob.bw:8443/bobnovatrack/nova/merchant/changeTerminalPswdInt
        createUser: https://bobnovatrackextapp-prd-service.bh.bob.bw:8443/novatrack/nova/merchant/createURM
        disputeAttchment: https://bobnovatrackextapp-prd-service.bh.bob.bw:8443/bobnovatrack/mportal/chargeback/downloadFile
        resetTerminalPwd: https://bobnovatrackextapp-prd-service.bh.bob.bw:8443/bobnovatrack/nova/merchant/resetTerminalPswdInt
        resetMerchantPwd: https://bobnovatrackextapp-prd-service.bh.bob.bw:8443/authentication/resetPassword
        serviceAttchment: https://bobnovatrackextapp-prd-service.bh.bob.bw:8443/bobnovatrack/mportal/request/downloadFile
        setTerminalPwd: https://bobnovatrackextapp-prd-service.bh.bob.bw:8443/bobnovatrack/nova/merchant/setTerminalPswdInt
        viewMerchantStatus: https://bobnovatrackextapp-prd-service.bh.bob.bw:8443/bobnovatrack/nova/merchant/viewStatus
      intApp:
        getDisputeAttchments: https://bobnovatrackintapp-prd-service.bh.bob.bw:8443/bobnovatrack-internal/disputeChargeback/getDisputeAttachment
      mpos:
        savemerchant: https://bobmpos-prd-service.bh.bob.bw:8443/mpos/onboard/save
        updateAmountMaster: https://bobmpos-prd-service.bh.bob.bw:8443/mpos/updateAmountMaster    
        updateTerminal: https://bobmpos-prd-service.bh.bob.bw:8443/mpos/updateTerminal
        updateTransactionStatusBatch: https://bobmpos-prd-service.bh.bob.bw:8443/mpos/updateTransactionStatusBatch
      urm:
        createUser: https://boburm-prd-service.bh.bob.bw:8443/user/add
        resetMerchantPwd: https://boburm-prd-service.bh.bob.bw:8443/authentication/resetPassword
        viewStatus: https://boburm-prd-service.bh.bob.bw:8443/user/viewStatus
        updateMidTidAndSerialNo: https://boburm-prd-service.bh.bob.bw:8443/userTerminal/updateMidTidAndSerialNo
        updateStatus: https://boburm-prd-service.bh.bob.bw:8443/user/updateStatus
        updateTerminalSerialNoByMidAndTid: https://boburm-prd-service.bh.bob.bw:8443/userTerminal/updateTerminalSerialNoByMidAndTid
        updateUserForUnLinkMid: https://boburm-prd-service.bh.bob.bw:8443/userTerminal/updateUserForUnLinkMid
      alert:
        sendmail: https://bobmessaging-prd-service.bh.bob.bw:8443/am/sendHtmlEmail
        sendmailandsms: https://bobmessaging-prd-service.bh.bob.bw:8443/am/sendHtmlEmailAndSms
        sendmailHtml: https://bobmessaging-prd-service.bh.bob.bw:8443/am/sendHtmlEmail
        sendsms: https://bobmessaging-prd-service.bh.bob.bw:8443/am/sendSms
      intUrm:
        configureAdminUserDetails: https://boburm-prd-service.bh.bob.bw:8443/internal/urm/user/configureAdminUserDetails
        createUser: https://boburm-prd-service.bh.bob.bw:8443/internal/urm/user/add
        updateNotificationDetails: https://boburm-prd-service.bh.bob.bw:8443/internal/urm/notification/updateUserNotifications
      cors:
        allowedOrigins:
        - https://bobr3portal-prd-service.bh.bob.bw:8443
        - https://bobr3portal-prd-service.bh.bob.bw:3006
        - https://bobr3portal-prd-service.bh.bob.bw
        - https://signage-prd-service.bh.bob.bw:8443
        - https://signage-prd-service.bh.bob.bw:3008
        - https://signage-prd-service.bh.bob.bw
        - https://bobnovatrackintportal-prd-service.bh.bob.bw:8443 
        - https://bobnovatrackintportal-prd-service.bh.bob.bw:3005
        - https://bobnovatrackintportal-prd-service.bh.bob.bw
        - https://bobnovatrackextportal-prd-service.bh.bob.bw:8443 
        - https://bobnovatrackextportal-prd-service.bh.bob.bw:3007
        - https://bobnovatrackextportal-prd-service.bh.bob.bw
        - https://bobburssimulator-prd-service.bh.bob.bw:8443 
        - https://bobburssimulator-prd-service.bh.bob.bw:3009
        - https://bobburssimulator-prd-service.bh.bob.bw