apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: prd
  # annotations:
  #   service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: keycloak
  type: LoadBalancer
  loadBalancerIP: 10.253.253.123
  ports:
  - port: 8443
    targetPort: 8443
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  namespace: prd
spec:
  replicas: 1
  serviceName: keycloak
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.3
          args: ["start"]
          env:
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
            - name: KEYCLOAK_USER
              value: admin
            - name: KEYCLOAK_PASSWORD
              value: admin
            - name: KC_HOSTNAME
              value: keycloack-prd-service.bh.bob.bw
            - name: KC_HTTPS_KEY_STORE_FILE
              value: /etc/x509/https/keycloack-prd-service.p12
            - name: KC_HTTPS_KEY_STORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ssl-keystore-secret
                  key: key-store-password
            - name: KC_HTTPS_KEY_STORE_TYPE
              value: PKCS12
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: "jdbc:postgresql://postgress-prd-service.bh.bob.bw:5432/keycloak?user=postgres&password=postgres"
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: keycloak-config
              mountPath: /opt/keycloak/conf
            - name: keystore
              mountPath: /etc/x509/https
            - name: keycloak-log
              mountPath: /opt/keycloak/logs
      volumes:
        - name: keycloak-config
          persistentVolumeClaim:
            claimName: keycloak-config
        - name: keycloak-data
          persistentVolumeClaim:
            claimName: keycloak-data
        - name: keycloak-log
          persistentVolumeClaim:
            claimName: keycloak-log
        - name: keystore
          secret:
            secretName: bh.bob.bw-keystore
