apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-config
  namespace: prd
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName: azurefile-csi
  volumeName: postgres-config
  resources:
    requests:
      storage: 16Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: prd
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName: azurefile-csi
  volumeName: postgres-data
  resources:
    requests:
      storage: 16Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-log
  namespace: prd
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName: azurefile-csi
  volumeName: postgres-log
  resources:
    requests:
      storage: 16Gi
