apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-api-gateway-data
  namespace: prd
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 16Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-api-gateway-content
  namespace: prd
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 16Gi
