apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-redis-0
  namespace: prd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: tkg-storage-policy-retain
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-redis-1
  namespace: prd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: tkg-storage-policy-retain
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-redis-2
  namespace: prd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: tkg-storage-policy-retain
  resources:
    requests:
      storage: 5Gi
