apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-config
  namespace: prd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: tkg-storage-policy
  resources:
    requests:
      storage: 16Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: prd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: tkg-storage-policy
  resources:
    requests:
      storage: 16Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-log
  namespace: prd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: tkg-storage-policy
  resources:
    requests:
      storage: 16Gi
